-- GDXU/GDXY Collaboration Hub Database Schema

-- 1. Market Data (For Custom Analytics)
-- Store OHLCV data from yfinance
CREATE TABLE market_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    open DECIMAL NOT NULL,
    high DECIMAL NOT NULL,
    low DECIMAL NOT NULL,
    close DECIMAL NOT NULL,
    volume BIGINT,
    UNIQUE(symbol, timestamp)
);

CREATE INDEX idx_market_data_symbol_timestamp ON market_data(symbol, timestamp DESC);

-- 2. AI Predictions
-- Store signals and metadata
CREATE TABLE ai_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    signal_type TEXT CHECK (signal_type IN ('safe', 'danger', 'neutral')),
    confidence DECIMAL DEFAULT 0,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_ai_predictions_timestamp ON ai_predictions(timestamp DESC);

-- 3. Analysis Reports
-- PDF/Images for team sharing
CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    file_url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Insight Feeds
-- Twitter-style timeline
CREATE TABLE feeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Realtime for feeds
ALTER PUBLICATION supabase_realtime ADD TABLE feeds;
ALTER PUBLICATION supabase_realtime ADD TABLE ai_predictions;

-- RLS (Row Level Security) - Basic Setup
-- Since it's a team tool, we assume authenticated users can read/write everything for now.
-- In production, you would use Auth.uid() checks.

ALTER TABLE market_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE feeds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON market_data FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for authenticated users" ON ai_predictions FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for authenticated users" ON reports FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for authenticated users" ON feeds FOR ALL TO authenticated USING (true) WITH CHECK (true);
