-- GDXU/GDXY Collaboration Hub Database Schema (Idempotent Version)

-- 1. Market Data
CREATE TABLE IF NOT EXISTS market_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    open DECIMAL NOT NULL,
    high DECIMAL NOT NULL,
    low DECIMAL NOT NULL,
    close DECIMAL NOT NULL,
    volume BIGINT,
    UNIQUE(symbol, timestamp)
);

CREATE INDEX IF NOT EXISTS idx_market_data_symbol_timestamp ON market_data(symbol, timestamp DESC);

-- 2. AI Predictions
CREATE TABLE IF NOT EXISTS ai_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    signal_type TEXT CHECK (signal_type IN ('safe', 'danger', 'neutral')),
    confidence DECIMAL DEFAULT 0,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_predictions_timestamp ON ai_predictions(timestamp DESC);

-- 3. Analysis Reports
CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    file_url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Insight Feeds
CREATE TABLE IF NOT EXISTS feeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    password TEXT, -- For deletion tracking
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Realtime (Ignore error if already added)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'feeds') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE feeds;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'ai_predictions') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE ai_predictions;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END $$;

-- RLS (Row Level Security)
ALTER TABLE market_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE feeds ENABLE ROW LEVEL SECURITY;

-- Basic Policies (Enable all access for anon & authenticated)
DO $$
BEGIN
    -- market_data
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'market_data' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON market_data FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    END IF;
    -- ai_predictions
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ai_predictions' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON ai_predictions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    END IF;
    -- reports
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'reports' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON reports FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    END IF;
    -- feeds
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'feeds' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON feeds FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;
ALTER TABLE feeds ADD COLUMN IF NOT EXISTS image_url TEXT; 
ALTER TABLE reports ADD COLUMN IF NOT EXISTS content TEXT;  
ALTER TABLE reports ADD COLUMN IF NOT EXISTS password TEXT; 
ALTER TABLE market_data ADD COLUMN IF NOT EXISTS interval TEXT DEFAULT '5m';  
ALTER TABLE market_data DROP CONSTRAINT IF EXISTS market_data_symbol_timestamp_key;  
ALTER TABLE market_data ADD CONSTRAINT market_data_symbol_interval_timestamp_key UNIQUE(symbol, interval, timestamp); 
CREATE TABLE IF NOT EXISTS predictions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), symbol TEXT NOT NULL, interval TEXT NOT NULL, model_name TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now(), prediction_data JSONB NOT NULL, confidence FLOAT, message TEXT); 
